### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by chaunceyjiang** [keijack/python-eureka-client#18]
192.168.2.204 - - [18/Sep/2019 14:09:26] "GET /client HTTP/1.1" 200 -
192.168.5.218 - - [18/Sep/2019 14:09:33] "GET /info HTTP/1.1" 200 -
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/home/chauncey/.local/lib/python3.6/site-packages/py_eureka_client/eureka_client.py", line 840, in __heartbeat
    self.__fetch_delta()
  File "/home/chauncey/.local/lib/python3.6/site-packages/py_eureka_client/eureka_client.py", line 893, in __fetch_delta
    self.__try_all_eureka_server(do_fetch)
  File "/home/chauncey/.local/lib/python3.6/site-packages/py_eureka_client/eureka_client.py", line 858, in __try_all_eureka_server
    fun(url)
  File "/home/chauncey/.local/lib/python3.6/site-packages/py_eureka_client/eureka_client.py", line 883, in do_fetch
    delta = get_delta(url, self.__regions)
  File "/home/chauncey/.local/lib/python3.6/site-packages/py_eureka_client/eureka_client.py", line 507, in get_delta
    return _get_applications_(_format_url(eureka_server) + "apps/delta", regions)
  File "/home/chauncey/.local/lib/python3.6/site-packages/py_eureka_client/eureka_client.py", line 381, in _get_applications_
    txt = http_client.load(_url, timeout=_DEFAULT_TIME_OUT)
  File "/home/chauncey/.local/lib/python3.6/site-packages/py_eureka_client/http_client.py", line 129, in load
    cafile=cafile, capath=capath, cadefault=cadefault, context=context).urlopen()
  File "/home/chauncey/.local/lib/python3.6/site-packages/py_eureka_client/http_client.py", line 94, in urlopen
    cadefault=self.cadefault, context=self.context)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

貌似获取注册中心配置时，超时了

**Comment by chaunceyjiang** [comment]
这是我自己的错误
