### ISSUE TITLE
"IndexError: list index out of range" for eureka server with domain name

### ISSUE THREAD

**Issue by rasisuku** [keijack/python-eureka-client#2]
getting index out of range, when we use eureka server url with domain name.  however it works with ip. 

Error trace:

Eureka Server Url:  http://myeureka.test.com:8077
Traceback (most recent call last):
  File "src\test_eureka.py", line 324, in <module>
    eureka_client.init_registry_client(eureka_server=Eureka_Server, app_name="eureka-test", instance_port=app_port)
  File "C:\Users\dummyuser\AppData\Roaming\Python\Python37\site-packages\py_eureka_client\eureka_client.py", line 788, in init_registry_client
    is_coordinating_discovery_server=is_coordinating_discovery_server)
  File "C:\Users\dummyuser\AppData\Roaming\Python\Python37\site-packages\py_eureka_client\eureka_client.py", line 569, in __init__
    self.__try_all_eureka_server(try_to_get_client_ip)
  File "C:\Users\dummyuser\AppData\Roaming\Python\Python37\site-packages\py_eureka_client\eureka_client.py", line 619, in __try_all_eureka_server
    fun(url)
  File "C:\Users\dummyuser\AppData\Roaming\Python\Python37\site-packages\py_eureka_client\eureka_client.py", line 558, in try_to_get_client_ip
    self.__instance_host = self.__instance_ip = RegistryClient.__get_instance_ip(url)
  File "C:\Users\dummyuser\AppData\Roaming\Python\Python37\site-packages\py_eureka_client\eureka_client.py", line 656, in __get_instance_ip
    _target_ = re_result[0]
IndexError: list index out of range

**Comment by keijack** [comment]
bug fixed, please update to the newest version. @rasisuku
