### ISSUE TITLE
[EurekaClient]-[line:704] -ERROR: error!

### ISSUE THREAD

**Issue by SimonWang00** [keijack/python-eureka-client#21]
错误日志如下：确认下该报错是不是代表Eureka Client无法connect到Eureka server？

[W 191023 10:46:08 eureka_client:644] Eureka server [http://192.168.5.207:8761/eureka/] is down, use next url to try.
[2019-10-23 10:46:08]-[EurekaClient]-[line:704] -ERROR: error!
Traceback (most recent call last):
  File "/application/anaconda3/lib/python3.7/site-packages/py_eureka_client/eureka_client.py", line 718, in send_heart_beat
    self.__try_all_eureka_server(lambda url: send_heart_beat(url, self.__instance["app"],
  File "/application/anaconda3/lib/python3.7/site-packages/py_eureka_client/eureka_client.py", line 654, in __try_all_eureka_server
    raise http_client.URLError("All eureka servers are down!")
urllib.error.URLError: <urlopen error All eureka servers are down!>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/application/anaconda3/lib/python3.7/site-packages/py_eureka_client/eureka_client.py", line 702, in register
    self.__try_all_eureka_server(lambda url: _register(url, self.__instance))
  File "/application/anaconda3/lib/python3.7/site-packages/py_eureka_client/eureka_client.py", line 654, in __try_all_eureka_server
    raise http_client.URLError("All eureka servers are down!")
urllib.error.URLError: <urlopen error All eureka servers are down!>

**Comment by keijack** [comment]
Yes, this error occurs when all the client cannot connect to even a euraka server.

**Comment by keijack** [comment]
no response for long time.
