### ISSUE TITLE
Django App is not able to register in Eureka Service Registry

### ISSUE THREAD

**Issue by RamanPndy** [keijack/python-eureka-client#27]
Hi,

I've created a Django application which must be registered with the Eureka Service.
I've also dockerized Django application and Eureka application and deploying through docker-compose.

I've given name discovery to the eureka service. but as soon as Django application tries itself to register with discovery(Eureka) service it shows the following errors:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 705, in register
    self.__try_all_eureka_server(lambda url: _register(url, self.__instance))
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 657, in __try_all_eureka_server
    raise http_client.URLError("All eureka servers are down!")
urllib.error.URLError: <urlopen error All eureka servers are down!>
[2020-07-13 18:38:13]-[EurekaClient]-[line:647] -WARNING: Eureka server [**http://discovery:8761/eureka**] is down, use next url to try.
2020-07-13 18:38:13,649 - EurekaClient - WARNING - Eureka server [**http://discovery:8761/eureka**] is down, use next url to try.
[2020-07-13 18:38:13]-[EurekaClient]-[line:725] -ERROR: Error!
2020-07-13 18:38:13,650 - EurekaClient - ERROR - Error!
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 721, in send_heart_beat
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 721, in send_heart_beat
    self.__try_all_eureka_server(lambda url: send_heart_beat(url, self.__instance["app"],
    self.__try_all_eureka_server(lambda url: send_heart_beat(url, self.__instance["app"],
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 657, in __try_all_eureka_server
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 657, in __try_all_eureka_server
    raise http_client.URLError("All eureka servers are down!")
    raise http_client.URLError("All eureka servers are down!")
urllib.error.URLError: <urlopen error All eureka servers are down!>
urllib.error.URLError: <urlopen error All eureka servers are down!>
2020-07-13 18:38:13,650 - EurekaClient - INFO - Cannot send heartbeat to server, try to register
[2020-07-13 18:38:13]-[EurekaClient]-[line:726] -INFO: Cannot send heartbeat to server, try to register
[2020-07-13 18:38:13]-[EurekaClient]-[line:647] -WARNING: Eureka server [http://discovery:8761/eureka] is down, use next url to try.
2020-07-13 18:38:13,651 - EurekaClient - WARNING - Eureka server [http://discovery:8761/eureka] is down, use next url to try.
[2020-07-13 18:38:13]-[EurekaClient]-[line:707] -ERROR: error!
2020-07-13 18:38:13,651 - EurekaClient - ERROR - error!
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 721, in send_heart_beat
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 721, in send_heart_beat
    self.__try_all_eureka_server(lambda url: send_heart_beat(url, self.__instance["app"],
    self.__try_all_eureka_server(lambda url: send_heart_beat(url, self.__instance["app"],
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 657, in __try_all_eureka_server
  File "/usr/local/lib/python3.8/site-packages/py_eureka_client/eureka_client.py", line 657, in __try_all_eureka_server
    raise http_client.URLError("All eureka servers are down!")
urllib.error.URLError: <urlopen error All eureka servers are down!>

Discovery (Eureka) Service is running on port 8761.

Please help me solving this issue or let me know if you require any further details.

**Comment by dinuta** [comment]
Hi man,

Depends on the eureka server you use. Some uses http://discovery:8761/eureka and others uses http://discovery:8080/eureka/v2

You can try with an updated eureka server dockerized by me and tested and see if works:

https://github.com/dinuta/netflixoss-eureka

There you have also docker-compose example.

Also there are times when the routing does not go through properly between docker world and your host network. You can restart your PC and try again.

**Comment by dinuta** [comment]
And also don't forget to add 15 second delay for the proper eureka boot. 
Generally it boots in 12 seconds.

If the eureka is not uo when your service tries to register, there you go :)

**Comment by RamanPndy** [comment]
@dinuta  Thanks for your response. now I'm using the docker image suggested by you and Django application is registering to eureka service now.
