### ISSUE TITLE
Issue when client init

### ISSUE THREAD

**Issue by brenramz** [keijack/python-eureka-client#41]
I'm getting this error on eureka client init bit also with init_discovery_client
`Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1177, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\H421926\Documents\DI\rabbitmq\env\lib\site-packages\py_eureka_client\eureka_client.py", line 1246, in __heartbeat
    time.sleep(self.__instance["leaseInfo"]["renewalIntervalInSecs"])
KeyError: 'leaseInfo'`

**Comment by keijack** [comment]
Thank you for submitting. This bug has been fixed, please upgrade to `0.8.9`.

**Comment by brenramz** [comment]
Thank you!

**Comment by keijack** [comment]
I close this, if you have any problem, please submit another issue.
